model_parameters:
  - {name: model_name, type: string, _: "multi-area-model"}  # for identifying the model, can be any unique string
  - {name: network_state, type: string, _: "metastable"}  # can be either "metastable" or "ground"
  - {name: record_spikes, type: string, _: "False"}  # whether to write spiking output to file, either True or False
  - {name: model_time_sim, type: float, _: "1000."}  # biological time to be simulated in ms
  - {name: model_time_presim, type: float, _: "500."}  # presimulation time for avoiding initial transients in ms
  - {name: scale_N, type: float, _: "1."}  # scaling the number of neurons, 1. -> original model
  - {name: scale_K, type: float, _: "1."}  # scaling the indegree, 1. -> original model
  - {name: rng_seed, _: "55"}  # rng seed for NEST, accepts a list in the format a,b,c,... for generating multiple runs
  - {name: scaling_type, _: "strong"}  # can be either weak or strong


machines:
  jureca: "jureca.yml"
