benchmarks:
  hpc_benchmark:
    repository: https://github.com/INM-6/beNNch-models.git  # TODO: Maybe define global repos somewhere which can be referenced at multiple places
    branch: main
    script_path: hpc_benchmark/hpc_benchmark3.py  # relative to model repo root
    config_path: hpc_benchmark/hpc_benchmark.yml  # relative to config repo root
  # microcircuit:
