repositories:
  base:
    url: https://github.com/JanVogelsang/CI-Bennch-config.git
    branch: root
extends:
  repo: base
  config_file: config2.yml
benchmarks:
  hpc_benchmark:
    machine_parameters:
      jureca:
        - {name: num_nodes, type: int, _: "1"}
        - {name: tasks_per_node, type: int, _: "2"}
        - {name: threads_per_task, type: int, _: "64"}
        - {name: walltime, type: string, _: "00:01:00"}
      jusuf:
        - {name: num_nodes, type: int, _: "1"}
        - {name: tasks_per_node, type: int, _: "2"}
        - {name: threads_per_task, type: int, _: "64"}
        - {name: walltime, type: string, _: "00:01:00"}
    model_parameters:
      - {name: model_time_sim, type: float, _: "90."}        # biological time to be simulated in ms
      - {name: model_time_presim, type: float, _: "10."}     # presimulation time for avoiding initial transients in ms
      - {name: scale, type: float, _: "0.01"}                 # scaling the number of neurons, 1. -> original model
      - {name: rng_seed, type: int, _: "42"}                  # rng seed for NEST, accepts a list in the format a,b,c,... for generating multiple runs
      - {name: kwds, separator: ;, type: string, _: "{}"}
  microcircuit:
    machine_parameters:
      jureca:
        - {name: num_nodes, type: int, _: "1"}
        - {name: tasks_per_node, type: int, _: "2"}
        - {name: threads_per_task, type: int, _: "64"}
        - {name: walltime, type: string, _: "00:01:00"}
      jusuf:
        - {name: num_nodes, type: int, _: "1"}
        - {name: tasks_per_node, type: int, _: "2"}
        - {name: threads_per_task, type: int, _: "64"}
        - {name: walltime, type: string, _: "00:01:00"}
    model_parameters:
      - {name: scale_N, type: float, _: "0.01"}  # scaling the number of neurons, 1. -> original model
      - {name: scale_K, type: float, _: "0.01"}  # scaling the indegree, 1. -> original model
      - {name: model_time_sim, type: float, _: "100."}  # biological time to be simulated in ms
      - {name: model_time_presim, type: float, _: "50."}  # in ms
      - {name: rng_seed, type: int, _: "55"}  # rng seed
      - {name: kwds, separator: ;, type: string, _: "{}"}
  multi_area:
    machine_parameters:
      jureca:
        - {name: num_nodes, type: int, _: "1"}
        - {name: tasks_per_node, type: int, _: "2"}
        - {name: threads_per_task, type: int, _: "64"}
        - {name: walltime, type: string, _: "00:01:00"}
      jusuf:
        - {name: num_nodes, type: int, _: "1"}
        - {name: tasks_per_node, type: int, _: "2"}
        - {name: threads_per_task, type: int, _: "64"}
        - {name: walltime, type: string, _: "00:01:00"}
    model_parameters:
      - {name: model_time_sim, type: float, _: "100."}  # biological time to be simulated in ms
      - {name: model_time_presim, type: float, _: "50."}  # presimulation time for avoiding initial transients in ms
      - {name: scale_N, type: float, _: "0.01"}  # scaling the number of neurons, 1. -> original model
      - {name: scale_K, type: float, _: "0.01"}  # scaling the indegree, 1. -> original model
      - {name: rng_seed, type: int, _: "55"}  # rng seed for NEST, accepts a list in the format a,b,c,... for generating multiple runs
      - {name: kwds, separator: ;, type: string, _: "{}"}
user_config:
  jureca:
    account: "jinb33"  # slurm account name for job submission
    partition: "dc-cpu"  # cluster partition, takes system default if left empty
  jusuf:
    account:  "icei-hbp-2020-0005"
    partition: "batch"
