benchmarks:
  hpc_benchmark:
    repository: https://github.com/INM-6/beNNch-models.git  # TODO: Maybe define global repos somewhere which can be referenced at multiple places
    branch: main
    model_path: hpc_benchmark  # path to model directory inside repository
    script_path: hpc_benchmark3.py  # relative to model path
    jube_path: hpc_benchmark/hpc_benchmark.yml  # relative to config repo root
    config_path: hpc_benchmark/hpc_benchmark_config.yml  # relative to config repo root
  # microcircuit:
user_config:
  hifis:
    account: "" # slurm account name for job submission
    email_address: "" # (optional) email address to which slurm sends START, END, FAIL emails for job progress info
    partition: "cpu" # (optional, required on some machines) cluster partition, takes system default if left empty
  jureca:
    project: "cjinb33"
    account: "jinb33" # slurm account name for job submission
    email_address: "j.vogelsang@fz-juelich.de" # (optional) email address to which slurm sends START, END, FAIL emails for job progress info
    partition: "dc-cpu" # (optional, required on some machines) cluster partition, takes system default if left empty 
requirements:  # TODO: Is this really the best place for such a config?
  hifis:
    pip: []
    modules: []
    apt:
      - cmake
      - gsl-bin
      - libgsl-dev
      - libboost-dev
      - cython3
      - libreadline-dev
      - python3-all-dev
      - python3-numpy
      - python3-scipy
      - python3-matplotlib
      - python3-nose
      - python3-junitparser
      - ipython3
      - python3-future
      - openmpi-bin
      - libopenmpi-dev
      - python3-mpi4py
      - libmusic-dev
      - music-bin
      - python3-pip
      - python3-pytest
      - python3-pytest-timeout
      - python3-pytest-xdist
