repositories:
  common:
    url: https://github.com/JanVogelsang/ci-bennch-models.git
    branch: master-thesis-axonal-delays
benchmarks:
  hpc_benchmark:
    repository: common
    model_dir: hpc_benchmark  # path to model directory inside repository
    config_path: hpc_benchmark/axonal_threads.yml  # relative to config repo root
user_config:
  jureca:
    compute-project: "cjinb33"  # account name for jutil env (for SCRATCH)
    data-project: "djinb33"  # account name for jutil env (for USERSOFTWARE)
    account: "slns"  # slurm account name for job submission
    email_address: "j.vogelsang@fz-juelich.de"  # (optional) email address to which slurm sends START, END, FAIL emails for job progress info
    partition: "dc-cpu"  # (optional, required on some machines) cluster partition, takes system default if left empty
dependencies: dependencies.yml