repositories:
  base:
    url: https://github.com/JanVogelsang/CI-Bennch-config.git
    branch: root
extends:
  repo: base
  config_file: config.yml
benchmarks:
  hpc_benchmark:
    machine_parameters:
      jusuf:
        num_nodes: "4,8,16,32,64"
        tasks_per_node: "8"
        threads_per_task: "16"
        walltime: "00:10:00"
      model_parameters:
        - {name: scale, type: float, _: "8.*$num_nodes"}                 # scaling the number of neurons, 1. -> original model
  microcircuit:
    machine_parameters:
      jusuf:
        num_nodes: "1"
        tasks_per_node: "1,2,3,4,5,6,7,8"
        threads_per_task: "'16,32,48,64,80,96,112,128' if $tasks_per_node == 1 else '16'"
        walltime: "00:05:00"
  multi_area:
    machine_parameters:
      jusuf:
        num_nodes: "4,8,16,32,64"
        tasks_per_node: "2"
        threads_per_task: "64"
        walltime: "01:00:00"
    model_parameters:
      - {name: model_time_sim, type: float, _: "10000."}  # biological time to be simulated in ms
      - {name: model_time_presim, type: float, _: "500."}  # presimulation time for avoiding initial transients in ms
      - {name: scale_N, type: float, _: "1."}  # scaling the number of neurons, 1. -> original model
      - {name: scale_K, type: float, _: "1."}  # scaling the indegree, 1. -> original model
      - {name: rng_seed, _: "654,55,92743"}  # rng seed for NEST, accepts a list in the format a,b,c,... for generating multiple runs
      - {name: kwds, separator: ;, type: string, _: "{}"}
user_config:
  jusuf:
    account:  "icei-hbp-2020-0005"
    partition: "batch"
