model_parameters:
  - {name: model_name, type: string, _: "hpc-benchmark"}  # for identifying the model, can be any unique string
  - {name: model_time_sim, type: float, _: "900."}        # biological time to be simulated in ms
  - {name: model_time_presim, type: float, _: "100."}     # presimulation time for avoiding initial transients in ms
  - {name: scale_N, type: float, _: "1."}                 # scaling the number of neurons, 1. -> original model
  - {name: record_spikes, type: string, _: "False"}       # whether to write spiking output to file, either True or False
  - {name: rng_seed, type: int, _: "55"}                  # rng seed for NEST, accepts a list in the format a,b,c,... for generating multiple runs
  - {name: scaling_type, type: string, _: "strong"}       # can be either weak or strong
run_parameters: []
machines:
  jureca: "jureca.yml"
